repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: check-yaml

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.18'
    hooks:
    -   id: isort

-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.4
    hooks:
    - id: shell-lint
