pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Docker credentials
  - group: Transifex credentials

steps:
  - script: |
      set -ex
      sudo systemctl stop mysql
      docker run -d -p 3306:3306 --name mysql --rm -e MYSQL_ROOT_PASSWORD=secret mysql:5.6.44 mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    displayName: Setup Mysql server


  - script: |
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    displayName: 'Log into docker registry'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)

  - script: docker pull derex/buildah
    displayName: 'Pull Buildah image'

  - script: |
      docker run -d \
        --name buildah \
        --privileged --security-opt="seccomp=unconfined" \
        --cap-add=ALL \
        -v /var/lib/containers/:/var/lib/containers/:rw,Z \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --mount type=bind,source=${HOME}/.docker,target=/root/.docker \
        --mount type=bind,source=${PWD},target=${PWD} \
        -e TRANSIFEX_USERNAME=$TRANSIFEX_USERNAME \
        -e TRANSIFEX_PASSWORD=$TRANSIFEX_PASSWORD \
        -e APK_CACHE=/var/cache/apk \
        -e NPM_CACHE=/var/cache/npm \
        -e PIP_CACHE=/var/cache/pip-alpine \
        derex/buildah \
        sleep 86400
    displayName: 'Start a docker image with buildah'
    env:
      TRANSIFEX_USERNAME: $(TRANSIFEX_USERNAME)
      TRANSIFEX_PASSWORD: $(TRANSIFEX_PASSWORD)

  - script: |
      docker exec buildah \
        bash -c "
          set -ex
          cd ${PWD}
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install ."
    displayName: 'Install derex.runner'

  - script: |
      docker exec buildah \
        bash -c "
          set -ex; cd ${PWD}
          IMAGE_DIR=derex/openedx/wheels
          IMAGE=\$(derex.builder image \$IMAGE_DIR)
          if curl --silent -f -lSL https://index.docker.io/v1/repositories/\$(echo \$IMAGE |sed -e 's|:|/tags/|'); then
            echo Image already present. Pulling.
            buildah pull \$IMAGE
          else
            derex.builder resolve \$IMAGE_DIR -v DEBUG
            buildah push \$IMAGE docker-daemon:\$IMAGE
          fi"
          docker push $(docker exec buildah derex.builder image derex/openedx/wheels) || true
    displayName: 'Build wheels image and push it'

  - script: |
      docker exec buildah \
        bash -c "
          set -ex; cd ${PWD}
          IMAGE_DIR=derex/openedx/nostatic
          IMAGE=\$(derex.builder image \$IMAGE_DIR)
          if curl --silent -f -lSL https://index.docker.io/v1/repositories/\$(echo \$IMAGE |sed -e 's|:|/tags/|'); then
            echo Image already present. Pulling.
            buildah pull \$IMAGE
          else
            derex.builder resolve \$IMAGE_DIR -v DEBUG
            buildah push \$IMAGE docker-daemon:\$IMAGE
          fi"
          docker push $(docker exec buildah derex.builder image derex/openedx/nostatic) || true
    displayName: 'Build nostatic image and push it'

  - script: |
      docker exec buildah \
        bash -c "
          set -ex; cd ${PWD}
          IMAGE_DIR=derex/openedx/nostatic-dev
          IMAGE=\$(derex.builder image \$IMAGE_DIR)
          if curl --silent -f -lSL https://index.docker.io/v1/repositories/\$(echo \$IMAGE |sed -e 's|:|/tags/|'); then
            echo Image already present. Pulling.
            buildah pull \$IMAGE
          else
            derex.builder resolve \$IMAGE_DIR -v DEBUG
            buildah push \$IMAGE docker-daemon:\$IMAGE
          fi"
          docker push $(docker exec buildah derex.builder image derex/openedx/nostatic-dev) || true
    displayName: 'Build nostatic-dev image and push it'

  - script: |
      docker exec buildah \
        bash -c "
          set -ex; cd ${PWD}
          IMAGE_DIR=derex/openedx/dev
          IMAGE=\$(derex.builder image \$IMAGE_DIR)
          if curl --silent -f -lSL https://index.docker.io/v1/repositories/\$(echo \$IMAGE |sed -e 's|:|/tags/|'); then
            echo Image already present. Pulling.
            buildah pull \$IMAGE
          else
            derex.builder resolve \$IMAGE_DIR -v DEBUG
            buildah push \$IMAGE docker-daemon:\$IMAGE
          fi"
          docker push $(docker exec buildah derex.builder image derex/openedx/dev) || true
    displayName: 'Build dev image and push it'

  - script: |
      docker exec buildah \
        bash -c "
          set -ex; cd ${PWD}
          IMAGE_DIR=derex/openedx/ironwood
          IMAGE=\$(derex.builder image \$IMAGE_DIR)
          echo '#''#vso[task.setvariable variable=LATEST_IMAGE]'\$IMAGE
          echo Made variable LATEST_IMAGE available for the following tasks. Value is \$IMAGE
          if curl --silent -f -lSL https://index.docker.io/v1/repositories/\$(echo \$IMAGE |sed -e 's|:|/tags/|'); then
            echo Image already present. Pulling.
            docker pull \$IMAGE
          else
            derex.builder resolve \$IMAGE_DIR -v DEBUG
            buildah push \$IMAGE docker-daemon:\$IMAGE
            # DO not push the image yet: the next step is going to add an empty db dump
          fi"
    displayName: 'Build ironwood image'

  - script: |
      set -ex
      export LATEST_IMAGE=$(echo "$LATEST_IMAGE" | sed -e "s/'//g")
      # If the dump is already there skip this step
      docker run --rm ${LATEST_IMAGE} ls -l /openedx/empty_dump.sql.bz2 && exit 0
      mysql -h localhost -psecret --protocol tcp -u root -e "CREATE DATABASE derex"
      DOCKER_RUN="docker run --add-host=mysql:$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') --rm"
      $DOCKER_RUN ${LATEST_IMAGE} ./manage.py lms --settings derex.base migrate
      $DOCKER_RUN -e SERVICE_VARIANT=cms ${LATEST_IMAGE} ./manage.py cms --settings derex.base migrate
      mkdir /tmp/image
      sudo mysqldump -h localhost -psecret --protocol tcp -u root derex > /tmp/image/empty_dump.sql
      bzip2 /tmp/image/empty_dump.sql
      echo -e "FROM ${LATEST_IMAGE}\nCOPY empty_dump.sql.bz2 /openedx/" > /tmp/image/Dockerfile
      docker build /tmp/image -t ${LATEST_IMAGE}
      docker push ${LATEST_IMAGE}
    displayName: 'Run migrations and save dump inside image'

  - script: |
      set -ex
      export LATEST_IMAGE=$(echo "$LATEST_IMAGE" | sed -e "s/'//g")
      # Run the restore_dump.py script: it should work and add the users fixture to the db
      docker run --add-host=mysql:$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') --rm ${LATEST_IMAGE} restore_dump.py
      # Make sure the fixtures ran and created test users
      mysql -h localhost --protocol tcp -u root -psecret derex -e "SELECT * from auth_user WHERE username='superuser'"|grep superuser
    displayName: 'Test the users fixture'

  - script: |
      export LATEST_IMAGE=$(echo "$LATEST_IMAGE" | sed -e "s/'//g")
      docker push ${LATEST_IMAGE}
    displayName: 'Push the image'

  - script: |
      export LATEST_IMAGE="$(echo "$LATEST_IMAGE" | sed -e "s/'//g")"
      export IMAGE_TO_PUSH="$(echo ${LATEST_IMAGE}|sed -e 's/:.*/:latest/')"
      docker tag "${LATEST_IMAGE}" "${IMAGE_TO_PUSH}"
      docker push "${IMAGE_TO_PUSH}"
    displayName: 'Also tag the image with the :latest tag and push it (only on master)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
