pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: docker pull derex/buildah
    displayName: 'Pull Buildah image'

  - script: |
      echo docker run --rm -v ${PWD}/cache/wheels:/dest derex/wheelhouse sh -c "cp -v /wheelhouse/*.whl /dest/; chown $(id -u):$(id -g) /dest/ -R"
      docker run --rm -v ${PWD}/cache/wheels:/dest derex/wheelhouse sh -c "cp -v /wheelhouse/*.whl /dest/; chown $(id -u):$(id -g) /dest/ -R"
    displayName: 'Put wheels cache in place'

  - script: |
      set -x
      set -e
      docker run \
        --rm --privileged --security-opt="seccomp=unconfined" \
        --cap-add=ALL \
        -v /var/lib/containers/:/var/lib/containers/:rw,Z \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ${PWD}:${PWD} \
        derex/buildah \
        bash -c "
          set -x
          set -e
          cd ${PWD}
          mkdir -p ${PWD}/cache/pip
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install .
          export WHEELS_CACHE=${PWD}/cache/wheels
          derex.builder resolve derex/openedx/wheels
          chown $(id -u) -R cache/wheels"
    displayName: 'Install derex.builder and build images'
