pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install git+https://github.com/Abstract-Tech/derex.builder.git
  displayName: 'Install derex.builder'

- script: |
    derex.builder resolve wheels
  displayName: 'Build openedx wheels image'
