jobs:
- job: Build_image
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    - group: Docker credentials
    - group: Transifex credentials

  steps:
    - script: DOCKER_BUILDKIT=1 docker build docker-definition/
      displayName: Build docker image
