jobs:
- job: Build_image
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    - group: Docker credentials
    - group: Transifex credentials
    - name: DOCKER_BUILDKIT
      value: '1'
    - name: DOCKER_IMAGES_SLUG
      value: juniper

  steps:
    - script: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      displayName: 'Log into docker registry'
      env:
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

    # These libgeos steps are commented out because they take 30 seconds to run in the warm case,
    # and they'll be seldom needed. Uncomment and let run once to re-prime the cache, if needed
    #- script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-libgeos --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-libgeos --target libgeos docker-definition/
    #  displayName: Build libgeos image

    #- script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-libgeos
    #  displayName: Push libgeos

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-base --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-libgeos --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-base --target base docker-definition/
      displayName: Build base image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-base
      displayName: Push base

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-builder --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-builder --target builder docker-definition/
      displayName: Build builder image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-builder
      displayName: Push builder

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-sourceonly --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-sourceonly --target sourceonly docker-definition/
      displayName: Build sourceonly image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-sourceonly
      displayName: Push sourceonly

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-wheels --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-wheels --target wheels docker-definition/
      displayName: Build wheels image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-wheels
      displayName: Push wheels

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-nostatic --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-nostatic --target nostatic docker-definition/
      displayName: Build nostatic image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-nostatic
      displayName: Push nostatic

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-nostatic --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-nostatic --target nostatic-dev docker-definition/
      displayName: Build nostatic-dev image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-nostatic
      displayName: Push nostatic

    - script: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t derex/edx-${DOCKER_IMAGES_SLUG}-dev --cache-from derex/edx-${DOCKER_IMAGES_SLUG}-dev --target dev docker-definition/
      displayName: Build dev image

    - script: docker push derex/edx-${DOCKER_IMAGES_SLUG}-dev
      displayName: Push dev
